<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Budget;
use App\Exports\BudgetExport;
use Illuminate\Support\Facades\Cache;
use Maatwebsite\Excel\Facades\Excel;

class BudgetController extends Controller
{
    public function store(Request $request)
    {
        Cache::forget('dashboard_data_user_' . auth()->id());

        // 1. Validar que la información esté correcta
        $validated = $request->validate([
            'title' => 'required|string|max:255',
            'income' => 'required|numeric|min:0|max:99999999.99|decimal:0,2',
            'currency' => ['sometimes', 'required', 'string', \Illuminate\Validation\Rule::in(array_keys(config('finance.currencies')))],
            'fixed_expenses_total' => 'required|numeric|min:0|max:99999999.99|decimal:0,2',
            'details' => 'required|array',
            'details.fixed' => 'sometimes|array|max:100',
            'details.fixed.*.name' => 'required|string|max:255',
            'details.fixed.*.amount' => 'required|numeric|min:0|max:99999999.99|decimal:0,2',
            'details.debts_deducted' => 'sometimes|numeric|in:0',
        ]);

        $fixed = $validated['details']['fixed'] ?? [];
        $fixedCents = array_key_exists('fixed', $validated['details'] ?? [])
            ? array_sum(array_map(fn ($item) => (int) round((float) $item['amount'] * 100), $fixed))
            : (int) round((float) $validated['fixed_expenses_total'] * 100);
        if ($fixedCents > 9999999999) {
            throw \Illuminate\Validation\ValidationException::withMessages(['fixed_expenses_total' => 'El total de gastos fijos supera el límite permitido.']);
        }
        $remaining = ((int) round((float) $validated['income'] * 100) - $fixedCents) / 100;

        // 2. Guardar en la base de datos amarrado al usuario que inició sesión
        Budget::create([
            'user_id' => auth()->id(),
            'title' => $request->title,
            'income' => $request->income,
            'currency' => $request->input('currency', $request->user()->preferred_currency),
            'fixed_expenses_total' => $fixedCents / 100,
            // Receipts and availability are generated by the server, never
            // accepted from the browser. Debt balances are deducted on payment.
            'details' => json_encode(['fixed' => $fixed, 'remaining' => $remaining, 'debts_deducted' => 0]),
        ]);

        // 3. Devolverlo a la página
        return redirect()->route('dashboard');
    }

    // Envía los datos a la nueva página de Historial
    public function history()
    {
        $misPresupuestos = \App\Models\Budget::where('user_id', auth()->id())->latest()->get();

        // Debts that have been fully paid off (balance brought to 0 or below)
        $defeatedBosses = \App\Models\Debt::where('user_id', auth()->id())
            ->where('balance', '<=', 0)
            ->orderByDesc('updated_at')
            ->get();

        return inertia('Historial', [
            'budgets'         => $misPresupuestos,
            'defeated_bosses' => $defeatedBosses,
        ]);
    }

    // Ahora acepta un ID para descargar cualquier Excel
    public function export($id = null)
    {
        if ($id) {
            // Si le pasamos un ID, busca ese presupuesto específico
            $budget = \App\Models\Budget::where('user_id', auth()->id())->findOrFail($id);
        } else {
            // Si no le pasamos ID (desde el Dashboard), busca el último
            $budget = \App\Models\Budget::where('user_id', auth()->id())->latest()->first();
        }

        if (!$budget) {
            return redirect()->back()->with('error', 'No hay datos para exportar.');
        }

        // Creamos un nombre de archivo dinámico con la fecha de esa batalla
        $nombreArchivo = 'Reporte_Batalla_' . date('Y-m-d', strtotime($budget->created_at)) . '.xlsx';
        return \Maatwebsite\Excel\Facades\Excel::download(new \App\Exports\BudgetExport($budget), $nombreArchivo);
    }
}
